services:
  - type: web
    name: e-response-backend
    env: python
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn e_response.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: e_response.settings
      - key: SECRET_KEY
        value: your-django-secret-key
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: e-response-backend-dev.onrender.com
      - key: DATABASE_URL
        value: optional-if-using-postgres
