# Generated by Django 5.1.7 on 2025-05-01 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_age_customuser_contact_number'),
        ('accounts', '0003_customuser_age_customuser_contact_number_and_more'),
    ]

    operations = [
    ]
